# Generated by Django 4.2.7 on 2023-12-29 07:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mascota', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato')], max_length=10)),
                ('raza', models.CharField(max_length=255)),
                ('nombre_mascota', models.CharField(max_length=255)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=10)),
                ('con_microchip', models.BooleanField(default=False)),
                ('esterilizado_castrado', models.BooleanField(default=False)),
                ('amigable_con_ninos', models.BooleanField(default=False)),
                ('amigable_con_perros', models.BooleanField(default=False)),
                ('fecha_adopcion_nacimiento', models.DateField()),
                ('sobre_tu_mascota', models.TextField()),
                ('nivel_energia', models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], max_length=10)),
                ('horario_alimentacion', models.CharField(choices=[('Manana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=20)),
                ('puede_dejar_solo', models.CharField(choices=[('1_2_horas', '1 a 2 horas'), ('2_4_horas', '2 a 4 horas'), ('4_12_horas', '4 a 12 horas'), ('12_24_horas', '12 a 24 horas')], max_length=20)),
                ('consume_medicacion', models.BooleanField(default=False)),
                ('medicamentos', models.CharField(blank=True, max_length=255)),
                ('detalles_medicacion', models.TextField(blank=True, null=True)),
                ('algo_mas_ninera_deba_saber', models.TextField()),
                ('informacion_veterinaria', models.TextField()),
                ('proveedor_seguro_mascotas', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('promo_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('data_sharing_enabled', models.BooleanField(default=False)),
                ('service_related_settings', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('cvc', models.CharField(max_length=3)),
                ('expiration_date', models.CharField(help_text='Formato DD/AA', max_length=5)),
                ('card_type', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='abcpet_app.userwallet')),
            ],
        ),
        migrations.CreateModel(
            name='MascotaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='mascota_photos/default.jpg', upload_to='mascota_photos/')),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abcpet_app.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='LoginDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ABCPetHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa_hospedaje', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(35000)])),
                ('tarifa_cuidado_casa', models.IntegerField(blank=True, null=True)),
                ('tarifa_guarderia', models.IntegerField(blank=True, null=True)),
                ('tarifa_paseo_perros', models.IntegerField(blank=True, null=True)),
                ('tarifa_vacaciones', models.IntegerField(blank=True, null=True)),
                ('tarifa_adicional_perros', models.IntegerField(blank=True, null=True)),
                ('tarifa_adicional_gatos', models.IntegerField(blank=True, null=True)),
                ('tarifa_estancia_prolongada', models.IntegerField(blank=True, null=True)),
                ('tarifa_aseo', models.IntegerField(blank=True, null=True)),
                ('tarifa_recogida_entrega', models.IntegerField(blank=True, null=True)),
                ('en_casa_tiempo_completo', models.BooleanField(blank=True, null=True)),
                ('dias_disponibles', models.CharField(blank=True, max_length=100)),
                ('aviso_previo', models.CharField(blank=True, max_length=100)),
                ('maximo_mascotas', models.IntegerField(blank=True, null=True)),
                ('tipos_mascotas', models.CharField(blank=True, max_length=200)),
                ('tipo_vivienda', models.CharField(blank=True, max_length=100)),
                ('tipo_jardin', models.CharField(blank=True, max_length=100)),
                ('expectativas_casa', models.TextField(blank=True)),
                ('mascotas_varias_familias', models.BooleanField(blank=True, null=True)),
                ('cachorros_menos_1_ano', models.BooleanField(blank=True, null=True)),
                ('perros_sin_entrenar', models.BooleanField(blank=True, null=True)),
                ('machos_no_castrados', models.BooleanField(blank=True, null=True)),
                ('hembras_no_esterilizadas', models.BooleanField(blank=True, null=True)),
                ('hembras_en_celo', models.BooleanField(blank=True, null=True)),
                ('perros_juguetones', models.BooleanField(blank=True, null=True)),
                ('gatos_sin_esterilizar_castrar', models.BooleanField(blank=True, null=True)),
                ('politica_cancelacion', models.CharField(blank=True, max_length=100)),
                ('email_referencia1', models.EmailField(blank=True, max_length=254)),
                ('email_referencia2', models.EmailField(blank=True, max_length=254)),
                ('anos_experiencia', models.IntegerField(blank=True, null=True)),
                ('titular_atractivo', models.CharField(blank=True, max_length=200)),
                ('experiencia_cuidado_mascotas', models.TextField(blank=True)),
                ('rutina_diaria', models.TextField(blank=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil')),
                ('foto_identificacion', models.ImageField(blank=True, null=True, upload_to='fotos_id')),
                ('comprobante_domicilio', models.ImageField(blank=True, null=True, upload_to='fotos_domicilio')),
                ('fotos_casa', models.ImageField(blank=True, null=True, upload_to='fotos_casa')),
                ('desea_verificacion', models.BooleanField(blank=True, null=True)),
                ('aprobado', models.BooleanField(blank=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
