# Generated by Django 4.2.7 on 2023-12-29 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abcpet_app', '0002_userprofile_legal_name_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='legal_name',
        ),
    ]
