# Generated by Django 4.2.7 on 2024-01-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcpet_app', '0007_remove_userprofile_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='region',
            field=models.CharField(blank=True, choices=[('Región Metropolitana de Santiago', 'Región Metropolitana de Santiago')], max_length=100, null=True, verbose_name='Región'),
        ),
    ]
