# Generated by Django 4.2.7 on 2024-01-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcpet_app', '0009_alter_userprofile_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='region',
            field=models.CharField(choices=[('Región Metropolitana de Santiago', 'Región Metropolitana de Santiago'), ('Otra', 'Otra')], default='Valor por Defecto', max_length=100, verbose_name='Región'),
        ),
    ]
