# Generated by Django 4.2.7 on 2024-01-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcpet_app', '0010_alter_userprofile_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='comuna',
            field=models.CharField(blank=True, choices=[('Alhué', 'Alhué'), ('Buin', 'Buin'), ('Calera de Tango', 'Calera de Tango')], max_length=255, null=True, verbose_name='Comuna'),
        ),
    ]
