# Generated by Django 4.2.7 on 2024-01-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcpet_app', '0011_alter_userprofile_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='comuna',
            field=models.CharField(choices=[('Alhué', 'Alhué'), ('Buin', 'Buin'), ('Calera de Tango', 'Calera de Tango'), ('Cerrillos', 'Cerrillos'), ('Cerro Navia', 'Cerro Navia'), ('Colina', 'Colina'), ('Conchalí', 'Conchalí'), ('Curacaví', 'Curacaví'), ('El Bosque', 'El Bosque'), ('El Monte', 'El Monte'), ('Estación Central', 'Estación Central'), ('Huechuraba', 'Huechuraba'), ('Independencia', 'Independencia'), ('Isla de Maipo', 'Isla de Maipo'), ('La Cisterna', 'La Cisterna'), ('La Florida', 'La Florida'), ('La Granja', 'La Granja'), ('La Pintana', 'La Pintana'), ('La Reina', 'La Reina'), ('Lampa', 'Lampa'), ('Las Condes', 'Las Condes'), ('Lo Barnechea', 'Lo Barnechea'), ('Lo Espejo', 'Lo Espejo'), ('Lo Prado', 'Lo Prado'), ('Macul', 'Macul'), ('Maipú', 'Maipú'), ('María Pinto', 'María Pinto'), ('Melipilla', 'Melipilla'), ('Ñuñoa', 'Ñuñoa'), ('Padre Hurtado', 'Padre Hurtado'), ('Paine', 'Paine'), ('Pedro Aguirre Cerda', 'Pedro Aguirre Cerda'), ('Peñaflor', 'Peñaflor'), ('Peñalolén', 'Peñalolén'), ('Pirque', 'Pirque'), ('Providencia', 'Providencia'), ('Pudahuel', 'Pudahuel'), ('Puente Alto', 'Puente Alto'), ('Quilicura', 'Quilicura'), ('Quinta Normal', 'Quinta Normal'), ('Recoleta', 'Recoleta'), ('Renca', 'Renca'), ('San Bernardo', 'San Bernardo'), ('San Joaquín', 'San Joaquín'), ('San José de Maipo', 'San José de Maipo'), ('San Miguel', 'San Miguel'), ('San Pedro', 'San Pedro'), ('San Ramón', 'San Ramón'), ('Santiago', 'Santiago'), ('Talagante', 'Talagante'), ('Tiltil', 'Tiltil'), ('Vitacura', 'Vitacura')], default='Valor por Defecto', max_length=255, verbose_name='Comuna'),
        ),
    ]
