# Generated by Django 4.2.7 on 2024-01-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcpet_app', '0012_alter_userprofile_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='region',
            field=models.CharField(choices=[('Región Metropolitana', 'Región Metropolitana'), ('Otra', 'Otra')], default='Valor por Defecto', max_length=100, verbose_name='Región'),
        ),
    ]
