# Generated by Django 4.2.7 on 2024-01-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcpet_app', '0015_customuser_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='abcpethost',
            name='comuna_host',
            field=models.CharField(choices=[('las_condes', 'Las Condes'), ('vitacura', 'Vitacura')], default='las_condes', max_length=255, verbose_name='Comuna para Host'),
        ),
        migrations.AddField(
            model_name='abcpethost',
            name='direccion',
            field=models.CharField(default='Valor por Defecto', max_length=200),
        ),
        migrations.AddField(
            model_name='abcpethost',
            name='region',
            field=models.CharField(default='Valor por Defecto', max_length=100),
        ),
    ]
