# Generated by Django 5.0.1 on 2024-01-16 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcpet_app', '0017_remove_abcpethost_tarifa_adicional_gatos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abcpethost',
            name='maximo_mascotas',
        ),
        migrations.RemoveField(
            model_name='abcpethost',
            name='tarifa_aseo',
        ),
        migrations.RemoveField(
            model_name='abcpethost',
            name='tarifa_recogida_entrega',
        ),
        migrations.RemoveField(
            model_name='abcpethost',
            name='tipos_mascotas',
        ),
        migrations.AddField(
            model_name='abcpethost',
            name='dias_disponibles_paseo',
            field=models.CharField(blank=True, choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=100, verbose_name='Días disponibles para paseo'),
        ),
        migrations.AddField(
            model_name='abcpethost',
            name='horarios_disponibles_paseo',
            field=models.CharField(blank=True, choices=[('6_11', '6 - 11 AM'), ('11_15', '11 AM - 15 PM'), ('15_22', '15 PM - 22 PM'), ('ninguno', 'Ninguno')], max_length=100, verbose_name='Horarios disponibles para paseo'),
        ),
        migrations.AddField(
            model_name='abcpethost',
            name='maximo_clientes_por_dia',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Máximo de clientes por día'),
        ),
        migrations.AddField(
            model_name='abcpethost',
            name='radio_servicio_paseo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Radio de servicio en KM'),
        ),
        migrations.AlterField(
            model_name='abcpethost',
            name='tarifa_cuidado_casa',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(35000)], verbose_name='Tarifa Cuidado en Casa'),
        ),
        migrations.AlterField(
            model_name='abcpethost',
            name='tarifa_guarderia',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(35000)], verbose_name='Tarifa Guardería'),
        ),
        migrations.AlterField(
            model_name='abcpethost',
            name='tarifa_hotel',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(35000)], verbose_name='Tarifa Hotel'),
        ),
        migrations.AlterField(
            model_name='abcpethost',
            name='tarifa_paseo_perros',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(35000)], verbose_name='Tarifa Paseo Perros'),
        ),
    ]
