# Generated by Django 5.0.1 on 2024-01-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcpet_app', '0018_remove_abcpethost_maximo_mascotas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=100, verbose_name='Día disponible para paseo')),
            ],
        ),
    ]
