# Generated by Django 5.0.1 on 2024-02-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcpet_app', '0019_diadisponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='abcpethost',
            name='verificado',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='abcpethost',
            name='servicio_en_casa_mascota',
            field=models.BooleanField(default=True, verbose_name='En casa de la mascota'),
        ),
        migrations.AlterField(
            model_name='abcpethost',
            name='servicio_guarderia',
            field=models.BooleanField(default=True, verbose_name='Guardería'),
        ),
        migrations.AlterField(
            model_name='abcpethost',
            name='servicio_hotel',
            field=models.BooleanField(default=True, verbose_name='Hotel'),
        ),
        migrations.AlterField(
            model_name='abcpethost',
            name='servicio_paseo_mascota',
            field=models.BooleanField(default=True, verbose_name='Paseo mascota'),
        ),
    ]
