# Generated by Django 5.0.1 on 2024-02-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcpet_app', '0020_abcpethost_verificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='desea_verificacion',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
