# Generated by Django 5.0.1 on 2024-02-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcpet_app', '0021_userprofile_desea_verificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='desea_verificacion',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
