# Generated by Django 5.0.1 on 2024-02-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcpet_app', '0022_alter_userprofile_desea_verificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abcpethost',
            name='verificado',
        ),
        migrations.AddField(
            model_name='abcpethost',
            name='estado_verificacion',
            field=models.CharField(choices=[('si', 'Verificado'), ('no', 'No Verificado'), ('pendiente', 'Pendiente de Verificación')], default='pendiente', max_length=20, verbose_name='Estado de Verificación'),
        ),
    ]
