# Generated by Django 5.0.1 on 2024-04-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcpet_app', '0026_alter_abcpethost_album_host_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='host_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='abcpethost',
            name='album_host_image',
        ),
        migrations.AddField(
            model_name='abcpethost',
            name='album_host_images',
            field=models.ImageField(blank=True, null=True, upload_to='album_host_images'),
        ),
    ]
