# Generated by Django 5.0.1 on 2024-06-19 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcpet_app', '0031_remove_abcpethost_album_host_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abcpethost',
            name='comuna_host',
            field=models.CharField(blank=True, choices=[('las_condes', 'Las Condes'), ('vitacura', 'Vitacura')], default='las_condes', max_length=255, verbose_name='Comuna para Host'),
        ),
        migrations.AlterField(
            model_name='abcpethost',
            name='direccion',
            field=models.CharField(blank=True, default='Valor por Defecto', max_length=200),
        ),
        migrations.AlterField(
            model_name='abcpethost',
            name='estado_verificacion',
            field=models.CharField(blank=True, choices=[('si', 'Verificado'), ('no', 'No Verificado'), ('pendiente', 'Pendiente de Verificación')], default='pendiente', max_length=20, verbose_name='Estado de Verificación'),
        ),
        migrations.AlterField(
            model_name='abcpethost',
            name='region',
            field=models.CharField(blank=True, choices=[('Metropolitana', 'Metropolitana')], default='Metropolitana', max_length=100),
        ),
        migrations.AlterField(
            model_name='abcpethost',
            name='servicio_en_casa_mascota',
            field=models.BooleanField(blank=True, default=True, verbose_name='En casa de la mascota'),
        ),
        migrations.AlterField(
            model_name='abcpethost',
            name='servicio_guarderia',
            field=models.BooleanField(blank=True, default=True, verbose_name='Guardería'),
        ),
        migrations.AlterField(
            model_name='abcpethost',
            name='servicio_hotel',
            field=models.BooleanField(blank=True, default=True, verbose_name='Hotel'),
        ),
        migrations.AlterField(
            model_name='abcpethost',
            name='servicio_paseo_mascota',
            field=models.BooleanField(blank=True, default=True, verbose_name='Paseo mascota'),
        ),
        migrations.AlterField(
            model_name='abcpethost',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diadisponible',
            name='dia',
            field=models.CharField(blank=True, choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=100, verbose_name='Día disponible para paseo'),
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
