# Generated by Django 5.0.1 on 2024-06-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcpet_app', '0032_alter_abcpethost_comuna_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
