name: Build and deploy Python app to Azure Web App - abcpet

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.17'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Collect static files
        run: |
          # Only run collectstatic if manage.py exists
          if [ -f "manage.py" ]; then
            python manage.py collectstatic --noinput || echo "Collectstatic command failed, continuing deployment"
          else
            echo "manage.py not found, skipping collectstatic"
          fi
          
      - name: Clean up before zipping
        run: |
          # Eliminar entornos virtuales y archivos de caché
          find . -type d -name __pycache__ -exec rm -rf {} +
          find . -type f -name "*.pyc" -delete
          # Si tienes un entorno virtual en nuevo_env, elimínalo
          if [ -d "abcpet_app/nuevo_env" ]; then
            rm -rf abcpet_app/nuevo_env
          fi

      - name: Log repository size
        run: |
          echo "Repository size before zip:"
          du -sh .
          echo "Largest directories:"
          du -h --max-depth=2 . | sort -hr | head -10

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Check zip size
        run: |
          echo "Zip file size:"
          du -sh release.zip

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Log deployment start time
        run: echo "Deployment started at $(date -u '+%Y-%m-%d %H:%M:%S UTC')"

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'abcpet'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_ABCPET }}
          package: release.zip
          clean: true
          restart: true

      - name: Log deployment end time
        run: echo "Deployment finished at $(date -u '+%Y-%m-%d %H:%M:%S UTC')"