# Docs for the Azusre Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More actualizacion GitHurb Ac2tions for Azure: https://github.com/Azure/actions

name: Build and deploy Python app to Azure Web App - abcpet

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Collect static files
        run: |
          # Only run collectstatic if manage.py exists
          if [ -f "manage.py" ]; then
            python manage.py collectstatic --noinput || echo "Collectstatic command failed, continuing deployment"
          else
            echo "manage.py not found, skipping collectstatic"
          fi
          
      # Optional: Add step to run tests here

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Necesario para OIDC
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: 84f00e77-3356-4190-b231-8fa4c917d733
          tenant-id: 9631a7f7-6b63-447f-bf60-8077cbcbb706
          subscription-id: e6f9c130-4130-4e1f-bddb-30e31c028335

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'abcpet'
          slot-name: 'Production'